### ISSUE TITLE
Breaking gold furnaces with fuel inside and a hopper below wont drop the fuel

### ISSUE THREAD

**Issue by vpontin** [cubex2/morefurnaces#4]
Steps:
- Place a gold furnace and inside put lava buckets and/or coal;
- Below place a hopper and below the hopper a chest;
- Break the furnace

The fuel is nowhere to see nor dropped on ground or inside hopper or chest.

MC 1.12.2
Forge 2691
MoreFurnaces 1.10.5
CXLibrary 1.6.1

**Comment by Artanis** [comment]
*None* of the furnaces return *any* contents, fuel, ingredients, or results, when broken, even if they don't have a hopper below them.

Tested in survival mode with all furnaces (copper, iron, silver, gold, diamond, nether, and obsidian), each broken with a diamond pick.

**Comment by vpontin** [comment]
Since @cubex2 seems to be away for a while (i've chatted with him on Twitter not long ago) i recommend to switch temporaly to [Iron Furnaces](https://minecraft.curseforge.com/projects/iron-furnaces) by @XenoMustache - this is more focused on be a Iron Chests equivalent for furnaces, but it did well its job.

[There's still unconfirmed issues](https://github.com/XenoMustache/ironfurnaces/issues/1) with this mod too, but nothing much frustrating than lost lava and buckets in a distraction.
