### ISSUE TITLE
[Issue] CXLibrary has no repository

### ISSUE THREAD

**Issue by Filmos** [cubex2/morefurnaces#6]
[CXLibrary](https://minecraft.curseforge.com/projects/cxlibrary) has no repository nor issue tracking service.
The link that is given on the project site is blocked.
This effectively prevents any modder (such as me) from upgrading this mod via pull requests, since no source code for coremod of this mod is available.

**Comment by Daniil1288** [comment]
@Filmos, just in case you don't get an answer like the other issues:
Try to contact the creator of this mod here (last active 4 hours ago): https://minecraft.curseforge.com/members/CubeX2
Or here: https://twitter.com/cubex2_

**Comment by Filmos** [comment]
Thanks, I'll try that!

**Comment by Filmos** [comment]
[It worked, now the repository is public.](https://github.com/cubex2/cxlibrary)
